name: flutter_web_auth_2
repository: https://github.com/yufei-tata/flutter_web_auth_2

packages:
  - flutter_web_auth_2
  - flutter_web_auth_2/example
  - flutter_web_auth_2_platform_interface
  - flutter_web_auth_2_platform_interface/example

command:
  version:
    linkToCommits: true
    workspaceChangelog: true

  bootstrap:
    usePubspecOverrides: true
